name: CI

on: [push, pull_request]

env:
  MOD_NAME: SkillToggles
  RELEASE_FILES: "*.py LICENSE"
  UNREALSDK_PYI_URL: https://gist.githubusercontent.com/Chronophylos/b77049094c20c6906ebe13d042a07998/raw/bf05d45e33c9f69f03eb8b90d72e85d4b2f61ff0/unrealsdk.pyi

jobs:
  check:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x86'
    - uses: RLNT/bl2-lint-action
      with:
        mod-name: ${{ env.MOD_NAME }}

  build:
    runs-on: ubuntu-latest
    needs: check
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Package as tar
      run: tar -czvf ${{ env.MOD_NAME }}.tar.gz $RELEASE_FILES
    - name: Package as zip
      run: zip -r ${{ env.MOD_NAME }}.zip $RELEASE_FILES

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            ${{ env.MOD_NAME }}.tar.gz
            ${{ env.MOD_NAME }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
